name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile classes
        uses: gradle/gradle-build-action@v2
        with:
          arguments: classes

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Contract test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: contractTest
